services:
  mariadb:
    build:
      context: ./requirements/mariadb
    networks:
      - my_network
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -u root -p$$(cat /run/secrets/sql_root_password)"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      - SQL_DATABASE
      - SQL_USER_NAME
      - SQL_PASSWORD_PATH=/run/secrets/sql_password
      - SQL_ROOT_PASSWORD_PATH=/run/secrets/sql_root_password
    secrets:
      - sql_root_password
      - sql_password
    volumes:
      - type: volume
        source: mariadb_vol
        target: /var/lib/mysql
        volume:
          nocopy: true

  wordpress:
    build:
      context: ./requirements/wordpress
    networks:
      - my_network
    restart: on-failure
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - WP_USER_NAME
      - WP_USER_MAIL
      - URL_SITE
      - DOMAIN_NAME
      - WP_ADMIN_NAME
      - WP_ADMIN_MAIL
      - SQL_DATABASE
      - SQL_USER_NAME
      - WP_DB_HOST=mariadb:3306
      - SQL_PASSWORD_PATH=/run/secrets/sql_password
      - WP_ADMIN_PASSWORD_FILE=/run/secrets/wp_admin_password
      - WP_USER_PASSWORD_FILE=/run/secrets/wp_user_password
    secrets:
      - sql_password
      - wp_admin_password
      - wp_user_password
    volumes:
      - wordpress_vol:/var/www/html

  nginx:
    build:
      context: ./requirements/nginx
    networks:
      - my_network
    restart: on-failure
    ports:
      - "443:443"
    volumes:
      - wordpress_vol:/var/www/html

secrets:
  sql_password:
    file: ../secrets/sql_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  sql_root_password:
    file: ../secrets/sql_root_password.txt

volumes:
  wordpress_vol:
    driver: local
    driver_opts:
        type: none
        o: bind
        device: /home/bruno/data/wordpress
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/bruno/data/mariadb

networks:
  my_network:
    driver: bridge
    name: Inception_network